import { useState, useRef } from 'react'



  
const getAwayData={
   Popular:[
     { location: "Canmore", subText: "Condo rentals" },
      { location: "Benalmadena", subText: "Holiday rentals" },
      { location: "Marbella", subText: "House rentals" },
      { location: "Mijas", subText: "House rentals" },
      { location: "Prescott", subText: "Vacation rentals" },
      { location: "Scottsdale", subText: "Apartment rentals" },
      { location: "Tucson", subText: "Vacation rentals" },
      { location: "Jasper", subText: "Vacation rentals" },
      { location: "Mountains view", subText: "Cabin rentals" },
      { location: "Devonport", subText: "Cottage rentals" },
      { location: "Mallacoota", subText: "Beach house  rentals" },
      { location: "Ibiza", subText: "Apartment rentals" },
      { location: "Anaheim", subText: "Vacation rentals" },
      { location: "Monterey", subText: "Cabin rentals" },
      { location: "Paso Robles", subText: "House rentals" },
      { location: "Santa Barbara", subText: "Apartment rentals" },
      { location: "Sonoma", subText: "Beach house rentals" },
      { location: "ber", subText: "Holiday rentals" },
      { location: "Dubai", subText: "Apartment rentals" },
      { location: "Birmingham", subText: "Vacation rentals" },
      { location: "Brighton", subText: "Vacation rentals" },
      { location: "Bude", subText: "Vacation rentals" },
      { location: "Newcastle upon Tyne", subText: "Vacation rentals" },
      { location: "Padstow", subText: "House rentals" },
      { location: "South West England", subText: "Cabin rentals" },
      { location: "Whitby", subText: "Vacation rentals" },
      { location: "Fort myers", subText: "Vacation rentals" },
      { location: "Jacksonville", subText: "Beach house rentals" },
      { location: "Kissimmee", subText: "Family-friendly rentals" },
      { location: "Longboatkey", subText: "Beach condo rentals" },
      { location: "Orlando", subText: "Cottage rentals" },
      { location: "St Petersburg", subText: "Vacation rentals" },
      { location: "St Augustine", subText: "Beach condo rentals" },
      { location: "The villages", subText: "Pet-friendly rentals" },
      { location: "Dahlonega", subText: "Cabin rentals" },
      { location: "Crete", subText: "House rentals" },
      { location: "Mykonos", subText: "Beach house rentals" },
      { location: "Santorini", subText: "Mansion rentals" },
      { location: "Oahu", subText: "Beachfront rentals" },
      { location: "Capri", subText: "Apartment rentals" },
      { location: "Bar Harbor", subText: "Pet-friendly rentals" },
      { location: "Mackinac Island", subText: "Vacation rentals" },
      { location: "St Joseph", subText: "Cottage rentals" },
      { location: "Larsmont", subText: "Cottage rentals" },
      { location: "Las Vegas", subText: "Vacation  rentals" },
      { location: "Madrid", subText: "Vacation rentals" },
      { location: "Santa Fe", subText: "Ski-in/ski-out rentals" },
      { location: "Bermagui", subText: "Pet-friendly rentals" },
      { location: "vans Head", subText: "Vacation rentals" },
      { location: "Sawtell", subText: "Vacation rentals" },
      { location: "Young", subText: "Vacation rentals" },
      { location: "Ocracoke", subText: "Pet-friendly rentals" },
      { location: "Florence", subText: "Cottage rentals" },
      { location: "Lakeside", subText: "Vacation rentals" },
      { location: "Lincoln City", subText: "Vacation rentals" },
      { location: "Paphos", subText: "Vacation rentals" },
      { location: "Maleny", subText: "Vacation rentals" },
      { location: "Stanthorpe", subText: "Pet-friendly rentals" },
      { location: "Newport", subText: "Vacation rentals" },
      { location: "Glasgow ", subText: "Vacation rentals" },
      { location: "Scottish Highlands", subText: "Vacation rentals" },
      { location: "St Andrews", subText: "Family-friendly rentals" },
      { location: "McLaren Vale", subText: "House rentals" },
      { location: "Wallaroo", subText: "Beachfront rentals" },
      { location: "Charleston", subText: "Apartment rentals" },
      { location: "Hvar", subText: "Apartment rentals" },
      { location: "Saint John", subText: "Vacation rentals" },
      { location: "Chattanooga", subText: "House rentals" },
      { location: "Concan", subText: "Vacation rentals" },
      { location: "Fredericksburg", subText: "Cottage rentals" },
      { location: "New Braunfels", subText: "Cottage rentals" },
      { location: "Rockport ", subText: "House rentals" },
      { location: "Waco", subText: "Apartment rentals" },
      { location: "Forest of Dean District", subText: "Vacation rentals" },
      { location: "Jersey ", subText: "Beach house rentals" },
      { location: "Lyme Regis", subText: "Chalet rentals" },
      { location: "Manchester", subText: "House rentals" },
      { location: "Seaview", subText: "Vacation  rentals" },
      { location: "Southwold", subText: "Vacation rentals" },
      { location: "Staithes", subText: "Cottage rentals" },
      { location: "Wells-next-the-Sea", subText: "House  rentals" },
      { location: "St. George", subText: "Apartment rentals" },
      { location: "Benidorm", subText: "Apartment rentals" },
      { location: "Barwon Heads", subText: "Vacation rentals" },
      { location: "Castlemaine", subText: "Vacation rentals" },
      { location: "Healesville", subText: "House rentals" },
      { location: "Marysville", subText: "Cottage rentals" },
      { location: "Sorrento", subText: "Beach house rentals" },
      { location: "Chincoteague", subText: "Beachfrontrentals" },
      { location: "Williamsburg", subText: "Vacation rentals" },
      { location: "Hay-on-Wye", subText: "Cottage rentals" },
      { location: "Llandudno", subText: "Apartment rentals" },
      { location: "Tenby Cabin", subText: "rentals" },

   ],
    
    "Arts & culture": [
      { location: "Phoenix", subText: "Condo rentals" },
      { location: "Hot Springs", subText: "Villa rentals" },
      { location: "Los Angeles", subText: "Apartment rentals" },
      { location: "San Diego", subText: "House rentals" },
      { location: "San Francisco", subText: "Vacation rentals" },
      { location: "Barcelona", subText: "Vacation rentals" },
      { location: "Prague", subText: "Vacation rentals" },
      { location: "Washinton", subText: "House rentals" },
      { location: "Keswick", subText: "Cabin rentals" },
      { location: "London", subText: "House rentals" },
      { location: "Scarborough", subText: "Vacation  rentals" },
      { location: "Sherwood Forest", subText: "Cabin rentals" },
      { location: "York", subText: "Family-friendly rentals" },
      { location: "Paris", subText: "House rentals" },
      { location: "Rhodes", subText: "Cottage rentals" },
      { location: "Nashville", subText: "Vacation rentals" },
      { location: "Dublin", subText: "House rentals" },
      { location: "Florence", subText: "House rentals" },
      { location: "Rome", subText: "House rentals" },
      { location: "Lisbon", subText: "House rentals" },
      { location: "Grand Isle", subText: "Pet-friendly rentals" },
      { location: "New Orleans", subText: "Pet-friendly rentals" },
      { location: "Martha's Vineyard", subText: "Vacation rentals" },
      { location: "South Haven", subText: "Condon rentals" },
      { location: "Duluth", subText: "Pet-friendly rentals" },
      { location: "Amsterdam", subText: "House rentals" },
      { location: "New York", subText: "Vacation rentals" },
      { location: "Nice", subText: "Cottage rentals" },
      { location: "Inverness", subText: "Apartment rentals" },
      { location: "Malaga", subText: "Apartment rentals" },
      { location: "Valencia", subText: "Villa rentals" },
      { location: "Split", subText: "House rentals" },
      { location: "Nashville", subText: "Rentals with pools" },
      { location: "Austin", subText: "Cabin rentals" },
      { location: "Houston", subText: "Vacation rentals" },
      { location: "Dartmouth", subText: "Chalet rentals" },
      { location: "Edinburgh", subText: "Apartment rentals" },
      { location: "Liverpool", subText: "Cottage rentals" },
      { location: "St Ives", subText: "House rentals" },
      { location: "Lake Powell", subText: "Vacation rentals" },
      { location: "Lake Anna", subText: "House rentals" },
      { location: "Leavenworth", subText: "Chalet rentals" },
      { location: "Seattle", subText: "Vacation rentals" },
    ],
    Outdoors: [
      { location: "Lake Martin", subText: "Apartment rentals" },
      { location: "Banff", subText: "Apartment rentals" },
      { location: "Nerja", subText: "Villa rentals" },
      { location: "Greer", subText: "Cabin rentals" },
      { location: "Lake Havasu City", subText: "Condo rentals" },
      { location: "Lake Powell", subText: "Vacation rentals" },
      { location: "North Rim", subText: "Vacation rentals" },
      { location: "Payson", subText: "Vacation rentals" },
      { location: "Pinetop-Lakeside", subText: "Cabin rentals" },
      { location: "Red Rock", subText: "Cabin rentals" },
      { location: "Dinner Plain", subText: "Pet-friendly  rentals" },
      { location: "Streaky Bay", subText: "Vacation rentals" },
      { location: "Emerald Lake", subText: "Cabin rentals" },
      { location: "Vancouver Island", subText: "Condo rentals" },
      { location: "Victoria", subText: "Apartment rentals" },
      { location: "Idyllwild-Pine Cove", subText: "House rentals" },
      { location: "Mammoth Lakes", subText: "Vacation rentals" },
      { location: "Palm Desert", subText: "Villa rentals" },
      { location: "Shaver Lake", subText: "Vacation rentals" },
      { location: "South Lake Tahoe", subText: "Vacation rentals" },
      { location: "Cultus Lake", subText: "Cabin rentals" },
      { location: "Georgian Bay", subText: "Vacation rentals" },
      { location: "Manitoulin Island", subText: "Cottage rentals" },
      { location: "Ottawa River", subText: "Cottage rentals" },
      { location: "The Blue Mountains", subText: "Vacation rentals" },
      { location: "West Kelowna", subText: "Beachfront rentals" },
      { location: "Gran Canaria", subText: "Villa rentals" },
      { location: "Lanzarote", subText: "Cottage rentals" },
      { location: "Castle Hill", subText: "Vacation rentals" },
      { location: "Aspen", subText: "Ski-in/ski-out rentals" },
      { location: "Colorado Springs", subText: "Vacation rentals" },
      { location: "Denver", subText: "Vacation rentals" },
      { location: "Durango", subText: "Pet-friendly rentals" },
      { location: "Estes Park", subText: "House rentals" },
      { location: "Grand Lake", subText: "Vacation rentals" },
      { location: "Keystone", subText: "Cabin rentals" },
      { location: "Vail", subText: "Condo rentals" },
      { location: "Winter Park", subText: "Condon rentals" },
      { location: "Salcombe", subText: "Cottage rentals" },
      { location: "Swanage", subText: "Apartment rentals" },
      { location: "Cape Coral", subText: "Vacation rentals" },
      { location: "Blue Ridge", subText: "Condon rentals" },
      { location: "Jekyll Island", subText: "Rentals with pools" },
      { location: "Lake Lanier", subText: "Family-friendly rentals" },
      { location: "Corfu", subText: "Apartment rentals" },
      { location: "McCall", subText: "Pet-friendly rentals" },
      { location: "Clear lake", subText: "Condo rentals" },
      { location: "Lough Eske", subText: "Vacation rentals" },
      { location: "Lake Cumberland", subText: "Lakehouse rentals" },
      { location: "Portland", subText: "House rentals" },
      { location: "South Portland", subText: "Vacation rentals" },
      { location: "Deep Creek Lake", subText: "Lakehouse rentals" },
      { location: "Lake Michigan Beach", subText: "House rentals" },
      { location: "Lakeside", subText: "Vacation  rentals" },
      { location: "Torch Lake", subText: "Lakehouse rentals" },
      { location: "Traverse City", subText: "Cottage rentals" },
      { location: "Upper Peninsula of Michigan", subText: "Vacation rentals" },
      { location: "Branson", subText: "Rentals with pools" },
      { location: "Lake of the Ozarks", subText: "Vacation rentals" },
      { location: "Big Sky", subText: "House rentals" },
      { location: "West Yellowstone", subText: "Condo rentals" },
      { location: "Moutain Charleston", subText: "Vacation rentals" },
      { location: "Cloudcroft", subText: "Cabin rentals" },
      { location: "Red River", subText: "Cabin rentals" },
      { location: "Bellingen", subText: "Cabin rentals" },
      { location: "Brunswick Heads", subText: "Pet-friendly rentals" },
      { location: "Adirondack Mountains", subText: "Vacation rentals" },
      { location: "Lake Placid", subText: "Apartment rentals" },
      { location: "Niagara Falls", subText: "Cottage rentals" },
      { location: "Bald Head Island", subText: "Cottage rentals" },
      { location: "Bryson City", subText: "Cabin rentals" },
      { location: "Emerald Isle", subText: "House rentals" },
      { location: "Lake Gaston", subText: "Cabin rentals" },
      { location: "Lake Lure", subText: "Vacation rentals" },
      { location: "Lake Norman of Catawba", subText: "Vacation rentals" },
      { location: "Mount Airy", subText: "Cabin rentals" },
      { location: "Oak Island", subText: "Beachfront rentals" },
      { location: "Geneva-on-the-Lake", subText: "Vacation rentals" },
      { location: "Medicine Park", subText: "Vacation rentals" },
      { location: "Turner Falls", subText: "Cabin rentals" },
      { location: "Muskoka Lakes", subText: "Vacation rentals" },
      { location: "Tobermory", subText: "Cabin rentals" },
      { location: "Bend", subText: "Cabin rentals" },
      { location: "Crater Lake", subText: "Cabin rentals" },
      { location: "Northern Oregon Coast Range", subText: "Vacation rentals" },
      { location: "Sunriver", subText: "Vacation rentals" },
      { location: "Lake Harmony", subText: "Vacation rentals" },
      { location: "Mount Pocono", subText: "Cabin rentals" },
      { location: "Mont-Tremblant", subText: "Condo rentals" },
      { location: "Aviemore", subText: "Cabin rentals" },
      { location: "Isle of Mull", subText: "Cottage rentals" },
      { location: "Robe", subText: "Vacation rentals" },
      { location: "Mountain Rest", subText: "Cabin rentals" },
      { location: "St Helens", subText: "Vacation rentals" },
      { location: "United States", subText: "Vacation rentals" },
      { location: "Canyon Lake", subText: "House rentals" },
      { location: "Lake Austin", subText: "House  rentals" },
      { location: "Lake Buchanan", subText: "Cabin rentals" },
      { location: "Betws-y-Coed", subText: "Vacation rentals" },
      { location: "Filey", subText: "Condo rentals" },
      { location: "Fort William", subText: "Cottage rentals" },
      { location: "Loch Lomond", subText: "Vacation rentals" },
      { location: "Port Isaac", subText: "Cottage rentals" },
      { location: "Moab", subText: "House rentals" },
      { location: "Mount Zion", subText: "Vacation rentals" },
      { location: "Moraira", subText: "Vacation rentals" },
      { location: "Inverloch", subText: "Vacation rentals" },
      { location: "Metung", subText: "Vacations rentals" },
      { location: "Mount Buller", subText: "Vacation rentals" },
      { location: "Port Campbell", subText: "Cottage rentals" },
      { location: "Wilsons Promontory", subText: "Vacation rentals" },
      { location: "Shenandoah", subText: "Cabin rentals" },
      { location: "Smith Mountain Lake", subText: "Vacation rentals" },
      { location: "Snowdon", subText: "Cottage rentals" },
      { location: "Lake Chelan", subText: "Vacation rentals" },
      { location: "Lake Crescent", subText: "Vacation rentals" },
      { location: "Lake Quinault", subText: "Cottage rentals" },
      { location: "Quinault", subText: "Vacation rentals" },
      { location: "Skamania", subText: "Vacation rentals" },
      { location: "Snowshoe", subText: "Vacation rentals" },
      { location: "Lake Geneva", subText: "Apartment rentals" },
      { location: "Wisconsin Dells", subText: "Vacation rentals" },
      { location: "United States", subText: "Vacation rentals" },
    ],
    Mountains: [
      { location: "Mentone", subText: "Cottage rentals" },
      { location: "Sedona", subText: "Pet-friendly rentals" },
      { location: "Helen", subText: "House rentals" },
      { location: "Pine Mountain", subText: "Vacation rentals" },
      { location: "Stone Mountain", subText: "Cabin rentals" },
      { location: "Island Park", subText: "Apartment rentals" },
      { location: "Blue Mountains", subText: "Chalet rentals" },
      { location: "Asheville", subText: "Rentals with pools" },
      { location: "Blowing Rock", subText: "Cottage rentals" },
      { location: "BBoone", subText: "Vacation rentals" },
      { location: "Hochatown", subText: "Vacation rentals" },
      { location: "Pigeon Forge", subText: "Vacation rentals" },
      { location: "Townsend", subText: "Vacation rentals" },
      { location: "Wears Valley", subText: "Vacation rentals" },
      { location: "Cabins", subText: "Vacation rentals" },
    ],
    Beach: [
      { location: "Dauphin Island", subText: "Beachfront rentals" },
      { location: "Fort Morgan", subText: "Vacation rentals" },
      { location: "Gulf Shores ", subText: "Vacation rentals" },
      { location: "Bruny Island", subText: "Vacation rentals" },
      { location: "Crescent Head", subText: "Beach house rentals" },
      { location: "Gerringong", subText: "Vacation rentals" },
      { location: "Hamilton Island", subText: "House rentals" },
      { location: "Lancelin ", subText: "Vacation rentals" },
      { location: "Melbourne Beach", subText: "Beachfront rentals" },
      { location: "Moonta Bay", subText: "Beachfront rentals" },
      { location: "Ocean Grove", subText: "House rentals" },
      { location: "Majorca", subText: "Apartment rentals" },
      { location: "Big Sur", subText: "Cabin rentals" },
      { location: "Bodega Bay", subText: "Vacation rentals" },
      { location: "Cambria", subText: "Beachfront rentals" },
      { location: "Cayucos", subText: "Vacation rentals" },
      { location: "Huntington Beach", subText: "Apartment rentals" },
      { location: "la Jolla Shores Beach", subText: "Vacation rentals" },
      { location: "Laguna Beach", subText: "Cottage rentals" },
      { location: "Long Beach", subText: "Cabin rentals" },
      { location: "Malibu", subText: "Bungalow rentals" },
      { location: "Mission Beach", subText: "Condo rentals" },
      { location: "Newport Beach", subText: "Bungalow rentals" },
      { location: "Oceanside Beach", subText: "house rentals" },
      { location: "Palm Springs", subText: "Apartment rentals" },
      { location: "Pismo Beach", subText: "House rentals" },
      { location: "Santa Cruz", subText: "Cottage rentals" },
      { location: "Santa Monica", subText: "Cottage rentals" },
      { location: "Sea Ranch", subText: "Pet-friendly rentals" },
      { location: "Playa Blanca", subText: "Vacation rentals" },
      { location: "Fuerteventura", subText: "Vacation rentals" },
      { location: "Puerto del Carmen", subText: "Villa rentals" },
      { location: "Tenerife", subText: "Cottage rentals" },
      { location: "Ayia Napa", subText: " Villa rentals" },
      { location: "Bethany Beach", subText: "Beach condo rentals" },
      { location: "Dewey Beach", subText: "Pet-friendly rentals" },
      { location: "Blackpool", subText: "Cabin rentals" },
      { location: "Isle of Wight", subText: "House rentals" },
      { location: "Newquay", subText: "Cabin rentals" },
      { location: "Weymouth", subText: "Apartment rentals" },
      { location: "Albufeira", subText: "Villa rentals" },
      { location: "Alys Beach", subText: " Pet-friendly rentals" },
      { location: "Anna Maria Island", subText: "Vacation rentals" },
      { location: "Bradenton", subText: "Apartment rentals" },
      { location: "Cape San Blas", subText: "House rentals" },
      { location: "Captiva", subText: "Vacation rentals" },
      { location: "Clearwater Beach", subText: "Beach house rentals" },
      { location: "Cocoa Beach", subText: "Condo rentals" },
      { location: "Daytona Beach", subText: "Pet-friendly rentals" },
      { location: "Destin  Beach", subText: "condo rentals" },
      { location: "Englewood", subText: "Condo rentals" },
      { location: "Fort Lauderdale", subText: "Mansion rentals" },
      { location: "Fort Myers Beach", subText: "House rentals" },
      { location: "Fort Walton Beach", subText: "House rentals" },
      { location: "Grayton Beach Beach", subText: "house rentals" },
      { location: "Gulf of Mexico", subText: "Vacation rentals" },
      { location: "Indian Rocks Beach", subText: "Bungalow rentals" },
      { location: "Islamorada", subText: "Rentals with pools" },
      { location: "Jacksonville Beach", subText: "Beach condo rentals" },
      { location: "Key Largo", subText: "Bungalow rentals" },
      { location: "Madeira Beach", subText: "Beach condo rentals" },
      { location: "Marathon", subText: "Rentals with pools" },
      { location: "Marco Island", subText: "Villa rentals" },
      { location: "Mexico Beach", subText: "Rentals with pools" },
      { location: "Miami Beach", subText: "Vacation rentals" },
      { location: "Miami", subText: "Villa rentals" },
      { location: "Miramar Beach", subText: "Cottage rentals" },
      { location: "Naples", subText: "Vacation rentals" },
      { location: "Navarre Beach", subText: "Beachfront rentals" },
      { location: "New Smyrna Beach", subText: "Apartment rentals" },
      { location: "Okaloosa Island", subText: "Beach condo rentals" },
      { location: "Panama City Beach", subText: "Vacation rentals" },
      { location: "Pensacola Beach", subText: "Vacation rentals" },
      { location: "Rosemary Beach", subText: "Vacation rentals" },
      { location: "Saint George Island", subText: "Condo rentals" },
      { location: "Santa Rosa Beach", subText: "Condo rentals" },
      { location: "Sarasota", subText: "Cottage rentals" },
      { location: "Seagrove Beach", subText: "Bungalow rentals" },
      { location: "Seaside", subText: "Beach house rentals" },
      { location: "South Beach", subText: "House rentals" },
      { location: "St. Augustine Beach", subText: " Beach house rentals" },
      { location: "St. Pete Beach", subText: "House rentals" },
      { location: "Tampa", subText: "Beach house rentals" },
      { location: "West Palm Beach", subText: "House rentals" },
      { location: "Bora-Bora", subText: "Apartment rentals" },
      { location: "Tybee Island", subText: "Apartment rentals" },
      { location: "Honolulu", subText: "Beach house rentals" },
      { location: "Kailua-Kona", subText: " Villa rentals" },
      { location: "Kapalua", subText: "Villa rentals" },
      { location: "Kauai", subText: "Family-friendly rentals" },
      { location: "Kihei", subText: "Cottage rentals" },
      { location: "Ko Olina Beach", subText: "Vacation rentals" },
      { location: "Maui", subText: "Cottage rentals" },
      { location: "Topsail Island", subText: "Vacation rentals" },
      { location: "Old Orchard Beach", subText: "House rentals" },
      { location: "Wells", subText: "Vacation rentals" },
      { location: "Cape Cod", subText: "Mansion rentals" },
      { location: "Nantucket", subText: "Vacation rentals" },
      { location: "Biloxi", subText: "Beach house rentals" },
      { location: "Avalon", subText: "Vacation rentals" },
      { location: "Jersey Shore", subText: "Beach house rentals" },
      { location: "North Wildwood", subText: " Beachfront rentals" },
      { location: "Ocean City", subText: "Cottage rentals" },
      { location: "Sea Isle City", subText: "Beachfront rentals" },
      { location: "Stone Harbor", subText: "Cottage rentals" },
      { location: "Hyams Beach", subText: "Beach house rentals" },
      { location: "Fire Island", subText: "Vacation rentals" },
      { location: "Montauk", subText: "Cottage rentals" },
      { location: "Ocean Beach", subText: "House rentals" },
      { location: "Atlantic Beach", subText: "Beach condo rentals" },
      { location: "Carolina Beach", subText: "Vacation rentals" },
      { location: "Corolla", subText: "Beachfront rentals" },
      { location: "Holden Beach", subText: " Condo rentals" },
      { location: "Kitty Hawk", subText: "Vacation rentals" },
      { location: "Kure Beach", subText: "Beachfront rentals" },
      { location: "Nags Head", subText: "Vacation rentals" },
      { location: "Ocean Isle Beach", subText: "Beach condo rentals" },
      { location: "Sunset Beach", subText: "Beachfront rentals" },
      { location: "Surf City", subText: "Vacation rentals" },
      { location: "Wilmington", subText: "Apartment rentals" },
      { location: "Wrightsville Beach", subText: "Beach condo rentals" },
      { location: "Sauble Beach", subText: "Chalet rentals" },
      { location: "Wasaga Beach", subText: "Vacation rentals" },
      { location: "Cannon Beach", subText: "Vacation rentals" },
      { location: "Seaside", subText: "House rentals" },
      { location: "Carvoeiro", subText: "Apartment rentals" },
      { location: "Gold Coast", subText: "Mansion rentals" },
      { location: "Moreton Island", subText: "Vacation rentals" },
      { location: "Block Island", subText: "Vacation rentals" },
      { location: "Puerto Peñasco", subText: "Vacation rentals" },
      { location: "Charleston Oceanfront Villas", subText: "Vacation rentals" },
      { location: "Edisto Beach", subText: "Beachfront rentals" },
      { location: "Folly Beach", subText: "House rentals" },
      { location: "Fripp Island", subText: "Vacation rentals" },
      { location: "Isle of Palms", subText: "Condo rentals" },
      { location: "Kiawah Island", subText: "Rentals with pools" },
      { location: "Myrtle Beach", subText: "Family-friendly rentals" },
      { location: "Pawleys Island", subText: "Beach house rentals" },
      { location: "Seabrook Island", subText: "Vacation rentals" },
      { location: "Sullivan's Island", subText: "Pet-friendly rentals" },
      { location: "Surfside Beach", subText: "Beach house rentals" },
      { location: "Alicante", subText: "Vacation rentals" },
      { location: "Costa Adeje", subText: "House rentals" },
      { location: "Costa del Sol Occidental", subText: "Vacation rentals" },
      { location: "Fuengirola", subText: "Vacation rentals" },
      { location: "Los Cristianos", subText: "Apartment rentals" },
      { location: "Corpus Christi", subText: "Beachfront rentals" },
      { location: "Port Aransas", subText: "Vacation rentals" },
      { location: "South Padre Island", subText: "Beachfront rentals" },
      { location: "Surfside Beach", subText: "House rentals" },
      { location: "Bournemouth", subText: "Villa rentals" },
      { location: "New Quay", subText: "Vacation rentals" },
      { location: "Anglesea", subText: "Vacation rentals" },
      { location: "Abersoch", subText: "Pet-friendly rentals" },
      { location: "Seabrook", subText: "Vacation rentals" },
      { location: "Jurien Bay", subText: "Pet-friendly rentals" },
    ],
    "Unique Stays": [
      { location: "Cabins", subText:  "United States" },
      { location: "Treehouses", subText: "United States" },
      { location: "Glamping", subText: "United States" },
      { location: "Tiny Houses", subText: "United States" },
      { location: "Beach Houses", subText: "United States" },
      { location: "Campers and RVs", subText: "United States" },
      { location: "Lakehouses", subText: "United States" },
      { location: "Yurt Rentals", subText: "United States" },
      { location: "Yurt Rentals", subText: "United Kingdom" },
      { location: "Castle Rentals", subText: "United States" },
      { location: "Houseboats", subText: "United States" },
      { location: "Holiday Caravans", subText: "United Kingdom" },
      { location: "Private Island Rentals", subText: "United States" },
      { location: "Farm Houses", subText: "United States" },
      { location: "Farm Cottages", subText: "United Kingdom" },
      { location: "Cabin Rentals", subText: "Australia" },
      { location: "Luxury Cabins", subText: "United Kingdom" },
      { location: "Luxury Cabins", subText: "United States" },
      { location: "Holiday Chalets", subText: "United Kingdom" },
      { location: "Cottage Rentals", subText: "United States" },
      { location: "Holiday Cottages", subText: "United Kingdom" },
      { location: "Mansion Rentals", subText: "United States" },
      { location: "Villa Rentals", subText: "United Kingdom" },
      { location: "Holiday Bungalows", subText: "United Kingdom" },
      { location: "Bungalow Rentals", subText: "United States" },
      { location: "Condo Rentals", subText: "United States" },
      { location: "Holiday Apartments", subText: "Australia" },
      { location: "Holiday Houses", subText: "United States" },
      { location: "Holiday Houses", subText: "United Kingdom" },
      { location: "Private Holiday Rentals", subText: "United Kingdom" },
      { location: "Big House Rentals", subText: "United States" },
      { location: "Big Cottages", subText: "Australia" },
      { location: "Large Villas", subText: "United Kingdom" },
      { location: "House Rentals with a Pool", subText: "United States" },
      { location: "Cabin Rentals with a Pool", subText: "United States" },
      { location: "Villas with a Pool", subText: "United Kingdom" },
      { location: "Apartments with a Hot Tub", subText: "United States" },
      {location: "Holiday Cottages with a Hot Tub",subText: "United Kingdom",},
      { location: "Beach Cabins", subText: "United States" },
      { location: "Beachfront Rentals", subText: " United States" },
      { location: "Beach Houses", subText: "United Kingdom" },
      { location: "Beach Villas", subText: "United Kingdom" },
      { location: "Coastal Cottages", subText: "United Kingdom" },
      { location: "Pet-Friendly Vacation Rentals", subText: "United States" },
      { location: "Pet-Friendly Beach Rental", subText: " United States" },
      { location: "Pet-Friendly Cabin Rentals", subText: "United States" },
      { location: "Dog-Friendly Cottages", subText: "United Kingdom" },
      { location: "Luxury Dog-Friendly Cottages", subText: "United Kingdom" },
    ],

    categories: [
      { location: "Amazing pools", subText:"" },
      { location: "Arctic", subText:"" },
      { location: "Camping", subText:"" },
      { location: "Campers", subText:"" },
      { location: "Castles", subText:"" },
      { location: "Containers", subText:""},
      { location: "Countryside", subText:"" },
      { location: "Design", subText:"" },
      { location: "Earth homes", subText:"" },
      { location: "Farms", subText:"" },
      { location: "National parks", subText:"" },
      { location: "Vineyards", subText:"" },
      { location: "OMG!", subText:"" },
      { location: "Tiny homes", subText:"" },
      { location: "Towers", subText:"" },
      { location: "Windmills", subText:"" },
      { location: "Luxe", subText:"" },
      { location: "Site Footer", subText:"" },
    ],

    "Things to do": [
      { location: "London", subText: "England" },
      { location: "Paris", subText: "Île-de-France" },
      { location: "New York", subText: "New York" },
      { location: "Barcelona", subText: "Catalonia" },
      { location: "İstanbul", subText: "İstanbul" },
      { location: "Bali", subText: "Indonesia" },
      { location: "Amsterdam", subText: "North Holland" },
      { location: "Miami", subText: "Florida" },
      { location: "Madrid", subText: "Community of Madrid" },
      { location: "Los Angeles", subText: "California" },
      { location: "Rome", subText: "Lazio" },
      { location: "Lisbon", subText: "Lisbon" },
      { location: "Tokyo", subText: "Tokyo" },
      { location: "Vienna", subText: "Vienna" },
      { location: "Athens", subText: "Greece" },
      { location: "Prague", subText: "Czechia" },
      { location: "Orlando", subText: "Florida" },
      { location: "Cancún", subText: "Quintana Roo" },
      { location: "Santorini", subText: "Greece" },
      { location: "Mexico City", subText: "Mexico City" },
      { location: "Venice", subText: "Veneto" },
      { location: "Playa del Carmen", subText: "Quintana Roo" },
      { location: "San Francisco", subText: "California" },
      { location: "Las Vegas", subText: "Nevada" },
      { location: "Boston", subText: "Massachusetts" },
      { location: "San Diego", subText: "California" },
      { location: "Chicago", subText: "Illinois" },
      { location: "Seattle", subText: "Washington" },
      { location: "Washington", subText: "District of Columbia" },
      { location: "Atlanta", subText: "Georgia" },
      { location: "Austin", subText: "Texas" },
      { location: "Maui", subText: "Hawaii" },
      { location: "New Orleans", subText: "Louisiana" },
      { location: "San Juan", subText: "San Juan" },
      { location: "O‘ahu", subText: "Hawaii" },
      { location: "Denver", subText: "Colorado" },
      { location: "Nashville", subText: "Tennessee" },
      { location: "Charleston", subText: "South Carolina" },
      { location: "Los Cabos", subText: "Baja California Sur" },
      { location: "Savannah", subText: "Georgia" },
      { location: "Dubai", subText: "Dubai" },
      { location: "Seoul", subText: "Seoul" },
      { location: "France" },
      { location: "Berlin", subText: "Berlin" },
      { location: "Canada" },
      { location: "Toronto", subText: "Ontario" },
      { location: "Switzerland" },
      { location: "Budapest", subText: " Hungary" },
      { location: " Spain" },
      { location: "Portugal" },
      { location: " United States" },
      { location: "Italy" },
      { location: "Greece" },
      { location: "Malta" },
      { location: "Türkiye" },
      { location: "Croatia" },
      { location: "Vancouver", subText: "British Columbia" },
      { location: "Mexico" },
      { location: "Milan", subText: "Lombardy" },
      { location: "Dublin", subText: "County Dublin" },
      { location: "Germany" },
      { location: "Costa Rica" },
      { location: "Manhattan", subText: "New York" },
      { location: "Japan" },
      { location: "Málaga", subText: "Andalusia" },
      { location: "Copenhagen", subText: "Denmark" },
      { location: "Montreal", subText: "Quebec" },
      { location: "Brussels", subText: "Brussels" },
      { location: "Valencia", subText: "Valencian Community" },
      { location: "Singapore" },
      { location: "Nice", subText: "Provence-Alpes-Côte d'Azur" },
      { location: "Munich", subText: "Bavaria" },
      { location: "Majorca", subText: "Balearic Islands" },
      { location: "Thailand" },
      { location: "Tulum", subText: "Quintana Roo" },
      { location: "Ireland" },
      { location: "Porto", subText: "Porto District" },
      { location: "England", subText: "United Kingdom" },
      { location: "Miami Beach", subText: "Florida" },
      { location: "Tenerife", subText: "Canary Islands" },
      { location: "Netherlands" },
      { location: "Zürich", subText: "Zurich" },
      { location: "Cyprus" },
      { location: "Stockholm", subText: "Stockholm County" },
      { location: "Cape Town", subText: "Western Cape" },
      { location: "Norway" },
      { location: "Sydney", subText: "New South Wales" },
      { location: "Tuscany", subText: "Italy" },
      { location: "Mykonos", subText: "Greece" },
      { location: "Hawaii", subText: "United States" },
      { location: "Florence", subText: "Tuscany" },
      { location: "Colombia" },
      { location: "Kyiv", subText: "Ukraine" },
      { location: "Antalya", subText: "Antalya" },
      { location: "Iceland" },
      { location: "Bangkok", subText: "Thailand" },
      { location: "Buenos Aires", subText: "Buenos Aires" },
      { location: "Bogotá", subText: "Bogota" },
      { location: "Warsaw", subText: "Masovian Voivodeship" },
    ],
    "Travel tips & inspiration": [
      { location: "Family travel hub", subText: "Tips and inspiration" },
      { location: "Family budget travel", subText: "Get there for less" },
      {
        location: "Vacation ideas for any budget",
        subText: "Make it special without making it spendy",
      },
      {
        location: "Travel Europe on a budget",
        subText: "How to take the kids to Europe for less",
      },
      {
        location: "Outdoor adventure",
        subText: "Explore nature with the family",
      },
      {
        location: "Bucket list national parks",
        subText: "Must-see parks for family travel",
      },
      {
        location: "Kid-friendly state parks",
        subText: "Check out these family-friendly hikes",
      },
    ],
    "Airbnb-friendly apartments": [
      { location: "Atlanta Metro " },
      { location: "Augusta", subText: "Georgia" },
      { location: "Austin Metro", subText: "Texas" },
      { location: "Birmingham", subText: "Alabama" },
      { location: "Boston Metro", subText: "Massachusetts" },
      { location: "Boulder", subText: "Colorado" },
      { location: "Charlotte", subText: "North Carolina" },
      { location: "Cincinnati", subText: "Ohio" },
      { location: "Columbia", subText: "South Carolina" },
      { location: "Dallas", subText: "Texas" },
      { location: "Denver", subText: "Colorado" },
      { location: "Gainesville", subText: "Florida" },
      { location: "Hoboken", subText: "New Jersey" },
      { location: "Houston Metro", subText: "Texas" },
      { location: "Indianapolis", subText: "Indiana" },
      { location: "Jacksonville", subText: "Florida" },
      { location: "Lacey", subText: "Washington" },
      { location: "Los Angeles", subText: "California" },
      { location: "Miami", subText: "Florida" },
      { location: "Orange County", subText: "California" },
      { location: "Marin County", subText: "California" },
      { location: "East Bay", subText: "California" },
      { location: "Orlando Metro", subText: "Florida" },
      { location: "Philadelphia Metro", subText: " Pennsylvania" },
      { location: "Phoenix", subText: "Arizona" },
      { location: "Pittsburgh", subText: "Pennsylvania" },
      { location: "Port Orange", subText: "Florida" },
      { location: "Portland", subText: "Oregon" },
      { location: "Raleigh", subText: "North Carolina" },
      { location: "Riverside", subText: "California" },
      { location: "Sacramento", subText: "California" },
      { location: "San Antonio", subText: "Texas" },
      { location: "San Diego", subText: "California" },
      { location: "San Francisco", subText: "California" },
      { location: "San Jose", subText: "California" },
      { location: "Seattle Metro", subText: "Washington" },
      { location: "San Francisco Peninsula", subText: " California" },
      { location: "Spokane ", subText: "Washington" },
      { location: "St. Augustine", subText: "Florida" },
      { location: "Tampa", subText: "Florida" },
      { location: "Ventura County", subText: "California" },
      { location: "Baltimore County", subText: "Maryland" },
      { location: "Washington Metro", subText: "District of Columbia" },
      { location: "West Palm Beach", subText: "Florida" },
    ],
     
}
type getAwayType = keyof typeof getAwayData;
export default function Cate() {
     // this is the state of the current selected tab
  const [selected, setSelected] = useState<getAwayType>("Popular");

  // this is the state of the see more
  const [seeMore, setSeeMore] = useState(false);

  // this holds a list of all navigations
  const navigation: getAwayType[] = [];

  // this is a for in loop that loops through the object and push the keys into the navigation array above
  for (const key in getAwayData) {
    const typedKey = key as getAwayType;
    navigation.push(typedKey);
  }
  function renderNavigation() {
    return navigation.map((item) => (
      <button
        key={item}
        onClick={() => {
          setSeeMore(false);
          setSelected(item);
        }}
        className={
          item === selected
            ? "text-black font-semibold pb-4 border-b-black border-b-2"
            : "pb-5 text-neutral-600"
        }
      >
        {item}
      </button>
      
    ));
  }
   function renderLocations() {
    const data = getAwayData[selected];

    return (
      <>
        {data.slice(0, seeMore ? data.length : 13).map((item) => (
          <div key={item.location} className='p-1 grid grid-cols-1'>
            <p className="text-black font-semibold ">{item.location}</p>
            <p className="text-neutral-600">{item.subText}</p>
          </div>
        ))}
        {!seeMore && (
          <button
            className="font-semibold "
            onClick={() => {
              setSeeMore(true);
            }}
          >
            See More
          </button>
          
        )}
        
      </>
    );
  }
  return (
    <main className="p-10">
      <h1 className="text-1xl font-semibold mb-3">
        Inspiration for future getaways
      </h1>
      
      <div className="flex gap-5 text-nowrap  ">{renderNavigation()}</div>
      
      <hr />
      <div className="grid grid-cols-2 sm:grid-cols-3  md:grid-cols-4 lg:grid-cols-6 gap-5 ">{renderLocations()}</div>
    </main>
  );
}
